### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by dobraMorda** [cadetill/gmlib_v1#15]
Hello!

How to clear cache in TWebBrowser in GMMap? I need to refresh file in TGMGroundOverlay but webbrowser keep cache and i can't refresh file.

Best Regards!
Patryk Kaminski

**Comment by cadetill** [comment]
Google Maps API works only using JavaScript. However, make sure that Offline property is set to False

**Comment by dobraMorda** [comment]
I had Offline in False mode. 
I force this problem with changing file name, but i have another problem. 
To refresh file I need to clear TGMGroundOverlay collection and Add item (file) again with new name and new bbox. 
Is possible to change Item Url and bbox? When i change URL and bbox of item, overlays is to disappear.

**Comment by dobraMorda** [comment]
I'm changing the filename and change it on URL. 

Closed;
