### ISSUE TITLE
Erro Página inicial aun no cargada, versão 1.5.4

### ISSUE THREAD

**Issue by medreis** [cadetill/gmlib_v1#3]
Olá Cadetill,

Atualizei o GmLib para a versão 1.5.4 , e esta ocorrendo o erro acima.

O erro ocorre na validação do FDocLoaded,  mas ainda não consegui identificar o porque ..

Para testes utilize o MegaDemo e tente criar uma nova TMARKER , o erro também ocorre.

Obrigado.

GMmap.pas
function TCustomGMMap.Check: Boolean;
begin
  if not Assigned(FWebBrowser) then
    raise Exception.Create(GetTranslateText('No se ha especificado el objeto WebBrowser', Language));

  if not FActive then
    raise Exception.Create(GetTranslateText('No está activo', Language));

   **if not FDocLoaded then
    raise Exception.Create(GetTranslateText('Página inicial aun no cargada', Language));**

  Result := not (csDesigning in ComponentState);
end;

**Comment by j1981** [comment]
tested on windows 7 x64 ie: 11.0.9600.18449 same error
tested on windows 7 x86 ie: 11.0.9600.17358 same error
This error is shown in ver 1.5.3 and 1.5.2
tested on windows 7 ie: 9.0.8112 (default on win7) works OK without showing the error message

**Comment by NEWSquamis** [comment]
I have same problem.
Win 10 x64 ie:11.1198.14393.0
This error is shown in ver 1.5.4 and 1.5.3

**Comment by j1981** [comment]
I did a small test. I changed line 5 from the file map.html from "\<meta http-equiv="X-UA-Compatible" content="IE=Edge"\>" to "\<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10"\>" and all wok fine on win10 ie: 11

**Comment by mehmetkocabas** [comment]
I tested your solution. it does not work. In project web browser froze on gray screen

**Comment by 8a9** [comment]
I tested this also, and got the same as @mehmetkocabas

**Comment by j1981** [comment]
after you change line you must run rc.cmd to create new resource files. then recompile component and install again. Library use resource file to store map.html and icons in exe

**Comment by mehmetkocabas** [comment]
The map does not open after adding your solution while opening the map in the original version. WebBrowser also freezes on the gray screen. I tried again now. I have already deleted the previous res files, and run rc.bat file, I have done what you said.

**Comment by j1981** [comment]
This is not a perfect solution, but I added this code to GMMap.pas and it works

// <-----added by me
function GetIEVersion: integer;
var res,main: string;
I: Integer;
begin
with TRegistry.Create do
try
RootKey := HKEY_LOCAL_MACHINE;
OpenKeyReadOnly('Software\Microsoft\Internet Explorer');
try
Res := ReadString('svcVersion');
if Res = '' then Res := ReadString('Version');
if Res = '' then raise Exception.Create('');
except
Res := '0';
end;
CloseKey;
finally
Free;
end;

for I := 1 to length(res) do
begin
if(res[i] = '.')then
begin
break;
end;
main := main + res[i];
end;
result := StrToInt(main);
end;
// end------>

function TCustomGMMap.GetBaseHTMLCode: string;
var
List: TStringList;
Stream: TResourceStream;
begin
Result := '';

List := TStringList.Create;
try
try
Stream := TResourceStream.Create(HInstance, RES_MAPA_CODE, RT_RCDATA);
List.LoadFromStream(Stream);
Result := List.Text;
//List.SaveToFile('d:\mapa.html');
Result := StringReplace(Result, C_API_KEY, FApiKey, []);
// <-----added by me
if(GetIEVersion3 >= 11)then
begin
Result := StringReplace(Result, '\<meta http-equiv="X-UA-Compatible" content="IE=edge"\>', '\<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10"\>', []);
end;
// end------>
finally
if Assigned(Stream) then FreeAndNil(Stream);
if Assigned(List) then FreeAndNil(List);
end;
except
raise Exception.Create(GetTranslateText('No se ha podido cargar el recurso', Language));
end;
end;

The Google Map apparently has some problem with the execution of the code in internet explorer 11 after last changes

**Comment by j1981** [comment]
test exe http://dox.bg/files/dw?a=c07510b52a

**Comment by mehmetkocabas** [comment]
I made changes but still did not work. I'm making a mistake somewhere, but I do not understand where. If you ask, you can also share the library folder with the res files you made.

**Comment by j1981** [comment]
library link http://dox.bg/files/dw?a=5bd032d290

**Comment by j1981** [comment]
if use megademo 
The page is reloaded permanently so it's gray the problem is in the code
procedure TMainFrm.GMMap1AfterPageLoaded(Sender: TObject; First: Boolean);
begin
  if First then
  begin
    sbStatus.Panels[0].Text := 'First Page Loaded';
    mEvents.Lines.Add('First Page Loaded');
    GMMap1.DoMap;
  end;{
  else
    sbStatus.Panels[0].Text := 'All Tiles Loadeds';}
end;
First always is true
Use a custom variable to indicate whether DoMap it is executed or not

var
firstLoad: boolean = false;

procedure TForm1.GMMap1AfterPageLoaded(Sender: TObject; First: Boolean);
begin
  if not firstLoad then
   begin
     Form1.GMMap1.RequiredProp.Center.lat := 42.6965;
    Form1.GMMap1.RequiredProp.Center.lng := 23.3215;
    try
      Form1.GMMap1.DoMap;      
      firstLoad := true;
    except

    end;
   end;
end;

**Comment by j1981** [comment]
recompiled megademo http://dox.bg/files/dw?a=f99f2cc353

**Comment by mehmetkocabas** [comment]
I do not use megademo. In project After the map is loaded, I add the markers via dataset to the WebBrowser. 

After the GMMap1AfterPageLoaded events  I call gmmap1.domap; commands but it is  explodes the error. 

I deleted the current library and installed your library, but still the problem did not improve.

**Comment by cadetill** [comment]
download the latest version from github and try again

Saludos
----------------------------
Xavier Martínez
cadetill

2017-05-17 23:18 GMT+02:00 mehmetkocabas <notifications@github.com>:
